# Generated by Django 5.1.3 on 2024-12-02 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="stripe_product_price_id",
        ),
    ]
